# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8c654ce80e7ffd5b4aa7277ed75d703bdca58f1233f838cccb34447ea380546b38fa38b16a3569f5e47a49d9476215945a8fae0025b635ba3b2c2f04536c05

test:
  secret_key_base: 0bfc709c6b0073488f6b92a9868c2835afe6e70ccc5077450b2621b972205c6ece3b664ffba7c9bd9a2f01a43231daa107426e39c9480d08f097bc9d6a9c9c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
